name: CI pipeline

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test
      - run: npm run build

      - name: Build Docker image
        run: docker build -t signmaster-backend .
      
      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with : 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Tag image
        run: docker tag signmaster-backend rizkym4l/signmaster-backend:latest
      
      - name: Push ke docker Hub
        run: docker push rizkym4l/signmaster-backend:latest

      - name: Notif to Disocrd -sukses
        if: success()
        run: |
         curl -H "Content-Type: application/json" \
         -d '{"content": "Pipline Berhasil"}' \
         ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notif to Discord - gagal
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "‚ùå Pipeline Gagal!\nRepo: ${{github.repository}}\nBranch: ${{github.ref_name}}\nCek: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

